/**
 * Regenerates `src/bundled_css.ts` from the files in `css/`.
 *
 * Usage: deno task gen
 */

const root = new URL("../", import.meta.url);
const files = [
  "index.css",
  "theme.css",
  "preflight.css",
  "utilities.css",
] as const;

function escapeTemplate(text: string): string {
  return text.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll(
    "${",
    "\\${",
  );
}

let out =
  `// Generated by scripts/gen_bundled_css.ts from the files in css/. Do not edit.
//
// theme.css and preflight.css are ported from Tailwind CSS
// (https://github.com/tailwindlabs/tailwindcss), MIT License,
// Copyright (c) Tailwind Labs, Inc. See the header of each file in css/.

/** The built-in stylesheets (SPEC §6.3), keyed by file name. */
export const BUNDLED_CSS: Record<string, string> = {
`;
for (const name of files) {
  const text = await Deno.readTextFile(new URL(`css/${name}`, root));
  out += `  "${name}": \`${escapeTemplate(text)}\`,\n`;
}
out += "};\n";

await Deno.writeTextFile(new URL("src/bundled_css.ts", root), out);
