(* Generates bundled_css.ml from the css directory given as the argument. *)

let read_file path =
  let ic = open_in_bin path in
  let n = in_channel_length ic in
  let s = really_input_string ic n in
  close_in ic;
  s

let () =
  let dir = Sys.argv.(1) in
  print_string "(* Generated by tools/gen_bundled.ml; do not edit. *)\n\nlet files = [\n";
  List.iter
    (fun name -> Printf.printf "  (%S, %S);\n" name (read_file (Filename.concat dir name)))
    [ "index.css"; "theme.css"; "preflight.css"; "utilities.css" ];
  print_string "]\n"
